import { describe, expect, it } from 'vitest'
import { EventType } from '@tanstack/ai/client'
import {
  GENERATION_EVENTS,
  updateGenerationResumeSnapshot,
} from '../src/generation-types'
import type { PersistedArtifactRef, StreamChunk } from '@tanstack/ai/client'
import type { GenerationResumeSnapshot } from '../src/generation-types'

const artifactRef: PersistedArtifactRef = {
  role: 'output',
  artifactId: 'artifact-1',
  threadId: 'thread-1',
  runId: 'run-1',
  name: 'image.png',
  mimeType: 'image/png',
  size: 1234,
  createdAt: '2026-07-06T00:00:00.000Z',
  source: {
    activity: 'image',
    path: 'thread-1/run-1/image.png',
    provider: 'test',
    model: 'image-model',
    mediaType: 'image',
  },
}

function reduceChunks(
  chunks: ReadonlyArray<StreamChunk>,
  initial?: GenerationResumeSnapshot,
): GenerationResumeSnapshot {
  let snapshot = initial
  for (const chunk of chunks) {
    snapshot = updateGenerationResumeSnapshot(snapshot, chunk)
  }
  if (!snapshot) {
    throw new Error('Expected at least one generation event')
  }
  return snapshot
}

describe('generation resume state reducer', () => {
  it('tracks thread and run from persisted generation events', () => {
    const snapshot = reduceChunks([
      {
        type: EventType.RUN_STARTED,
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 1,
      },
      {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.PROGRESS,
        value: { progress: 50, message: 'Halfway' },
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 2,
      },
    ])

    expect(snapshot).toMatchObject({
      resumeState: {
        threadId: 'thread-1',
        runId: 'run-1',
      },
      status: 'running',
      lastEvent: {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.PROGRESS,
      },
    })
  })

  it('stores generation artifacts as persisted refs only', () => {
    const snapshot = reduceChunks([
      {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.ARTIFACTS,
        value: [
          artifactRef,
          {
            b64Json: 'raw-media-bytes',
            url: 'data:image/png;base64,raw-media-bytes',
          },
        ],
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 1,
      },
    ])

    expect(snapshot.pendingArtifacts).toEqual([artifactRef])
    expect(JSON.stringify(snapshot)).not.toContain('raw-media-bytes')
    expect(snapshot.activity).toBe('image')
  })

  it('sanitizes artifact refs before storing them in resume snapshots', () => {
    const unsafeArtifactRef = {
      ...artifactRef,
      externalUrl: 'data:image/png;base64,raw-artifact-bytes',
      b64Json: 'raw-artifact-bytes',
      blob: new Blob(['raw-artifact-bytes']),
      url: `https://example.com/${'x'.repeat(4096)}`,
      source: {
        ...artifactRef.source,
        extraRawField: 'raw-artifact-bytes',
      },
    }

    const snapshot = reduceChunks([
      {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.ARTIFACTS,
        value: [unsafeArtifactRef],
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 1,
      },
      {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.RESULT,
        value: {
          id: 'result-1',
          artifacts: [unsafeArtifactRef],
        },
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 2,
      },
    ])

    expect(snapshot.pendingArtifacts).toEqual([artifactRef])
    expect(snapshot.result?.artifacts).toEqual([artifactRef])
    expect(JSON.stringify(snapshot)).not.toContain('raw-artifact-bytes')
    expect(JSON.stringify(snapshot)).not.toContain('b64Json')
    expect(JSON.stringify(snapshot)).not.toContain('extraRawField')
  })

  it('stores terminal result metadata without raw generated bytes', () => {
    const snapshot = reduceChunks([
      {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.RESULT,
        value: {
          id: 'result-1',
          model: 'image-model',
          images: [
            {
              b64Json: 'raw-image-bytes',
              url: 'data:image/png;base64,raw-image-bytes',
              revisedPrompt: 'clean prompt',
            },
          ],
          artifacts: [artifactRef],
        },
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 2,
      },
      {
        type: EventType.RUN_FINISHED,
        threadId: 'thread-1',
        runId: 'run-1',
        finishReason: 'stop',
        timestamp: 3,
      },
    ])

    expect(snapshot.resumeState).toBeNull()
    expect(snapshot.status).toBe('complete')
    expect(snapshot.result).toMatchObject({
      id: 'result-1',
      model: 'image-model',
      artifacts: [artifactRef],
    })
    expect(JSON.stringify(snapshot)).not.toContain('raw-image-bytes')
    expect(JSON.stringify(snapshot)).not.toContain('b64Json')
  })

  it('omits non-durable and oversized result URLs from resume snapshots', () => {
    const oversizedUrl = `https://example.com/${'x'.repeat(4096)}`
    const unsafeUrls = [
      'data:image/png;base64,raw-image-bytes',
      'blob:https://example.com/raw-image-bytes',
      oversizedUrl,
    ]

    for (const url of unsafeUrls) {
      const snapshot = reduceChunks([
        {
          type: EventType.CUSTOM,
          name: GENERATION_EVENTS.RESULT,
          value: {
            id: 'result-1',
            model: 'image-model',
            url,
            artifacts: [artifactRef],
          },
          threadId: 'thread-1',
          runId: 'run-1',
          timestamp: 2,
        },
      ])

      expect(snapshot.result).toMatchObject({
        id: 'result-1',
        model: 'image-model',
        artifacts: [artifactRef],
      })
      expect(snapshot.result).not.toHaveProperty('url')
      expect(JSON.stringify(snapshot)).not.toContain('raw-image-bytes')
      expect(JSON.stringify(snapshot)).not.toContain(oversizedUrl)
    }
  })

  it('clears resume state and stores lightweight error metadata on terminal errors', () => {
    const snapshot = reduceChunks([
      {
        type: EventType.RUN_STARTED,
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 1,
      },
      {
        type: EventType.RUN_ERROR,
        threadId: 'thread-1',
        runId: 'run-1',
        message: 'Generation failed',
        code: 'provider_error',
        error: { message: 'legacy message' },
        timestamp: 2,
      },
    ])

    expect(snapshot).toMatchObject({
      resumeState: null,
      status: 'error',
      error: {
        message: 'Generation failed',
        code: 'provider_error',
      },
    })
  })

  it('does not model explicit stop as durable cancel state', () => {
    const snapshot = reduceChunks([
      {
        type: EventType.RUN_STARTED,
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 1,
      },
    ])

    expect(snapshot.status).toBe('running')
    expect(snapshot).not.toHaveProperty('cancelled')
    expect(snapshot).not.toHaveProperty('cancelEndpoint')
  })
})
