name: PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Tools
        uses: TanStack/config/.github/setup@bfa16483f70e69805e1ea4eee29988b133d2aa46 # main
      - name: Get base and head commits for `nx affected`
        uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1 # v4.4.0
        with:
          main-branch-name: main
      - name: Run Checks
        run: pnpm run test:pr
  preview:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Setup Tools
        uses: TanStack/config/.github/setup@bfa16483f70e69805e1ea4eee29988b133d2aa46 # main
      - name: Build Packages
        run: pnpm run build:all
      - name: Publish Previews
        run: pnpx pkg-pr-new publish --pnpm './packages/*'
  version-preview:
    name: Version Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Setup Tools
        uses: TanStack/config/.github/setup@bfa16483f70e69805e1ea4eee29988b133d2aa46 # main
      - name: Changeset Preview
        uses: TanStack/config/.github/changeset-preview@bfa16483f70e69805e1ea4eee29988b133d2aa46 # main
